VHG-31 Add build step to Dockerfiles

diff --git a/apps/vhg/Dockerfile b/apps/vhg/Dockerfile
--- a/apps/vhg/Dockerfile
+++ b/apps/vhg/Dockerfile
@@ -1,40 +1,84 @@
-# Install dependencies only when needed
 # `--platform=linux/amd64` needed to resolve this issue: https://stackoverflow.com/questions/74705475/aws-ecs-exec-usr-local-bin-docker-entrypoint-sh-exec-format-error
-FROM --platform=linux/amd64 docker.io/node:lts-alpine as dependencies
+# FROM --platform=linux/amd64 docker.io/node:lts-alpine as base
+# FROM --platform=linux/amd64 docker.io/node:20-slim as base
+FROM --platform=linux/amd64 docker.io/node:20-slim as base
+# ENV PNPM_HOME="/usr/local/pnpm"
+# ENV PNPM_HOME="/pnpm"
+# ENV PATH="$PNPM_HOME:$PATH"
+# RUN corepack enable
 
-RUN apk add --no-cache libc6-compat
-RUN apk add g++ make py3-pip
-WORKDIR /usr/src/app
+# Install dependencies only when needed
+FROM base AS deps
+# RUN apk add --no-cache libc6-compat
+# RUN apk add g++ make py3-pip
+# WORKDIR /usr/src/app
+WORKDIR /app
 # TODO: Check if this should be using the root package.json instead
 # COPY ./dist/apps/vhg/package.json ./
+# COPY ./package.json pnpm-lock.yaml* ./
+# COPY pnpm-lock.yaml ./
 COPY ./package.json ./
 COPY ./prisma ./prisma
-RUN npm install --omit=dev --legacy-peer-deps
+# RUN npm install --omit=dev --legacy-peer-deps
+RUN npm install --omit=dev
+# RUN \
+  # if [ -f pnpm-lock.yaml ]; then pnpm i --prod --frozen-lockfile; \
+  # else echo "Lockfile not found." && exit 1; \
+  # fi
+# RUN pnpm fetch --prod
 # Keep the prisma version in sync the @prisma/client dependency's version
 RUN npm install -g prisma@5.3.1
+# RUN pnpm add -g prisma@5.3.1
 RUN prisma generate
 
-# Production image, copy all the files and run next
-# `--platform=linux/amd64` needed to resolve this issue: https://stackoverflow.com/questions/74705475/aws-ecs-exec-usr-local-bin-docker-entrypoint-sh-exec-format-error
-FROM --platform=linux/amd64 docker.io/node:lts-alpine as runner
-
-ARG CONTAINER_CONTEXT=dist/apps/vhg
-
-RUN echo "Container context for runner: $CONTAINER_CONTEXT"
-
-RUN apk add --no-cache dumb-init
+# Rebuild the source code only when needed
+FROM base AS builder
+# WORKDIR /usr/src/app
+WORKDIR /app
+# COPY --from=deps /usr/src/app/node_modules ./node_modules
+COPY --from=deps /app/node_modules ./node_modules
+COPY . .
 
 ENV NEXT_TELEMETRY_DISABLED 1
 
-WORKDIR /usr/src/app
+# RUN pnpm add -g nx@18.2.4
+RUN npm install -g nx@18.2.4
+
+# RUN \
+#   if [ -f pnpm-lock.yaml ]; then pnpm exec nx build vhg; \
+#   else echo "Lockfile not found." && exit 1; \
+#   fi
+RUN nx build vhg --verbose
+
+# Production image, copy all the files and run next
+FROM base as runner
+
+# ARG CONTAINER_CONTEXT=dist/apps/vhg
+
+# RUN echo "Container context for runner: $CONTAINER_CONTEXT"
+
+# RUN apk add --no-cache dumb-init
+
+ENV NODE_ENV=production
+ENV NEXT_TELEMETRY_DISABLED 1
+
+# WORKDIR /usr/src/app
+WORKDIR /app
 
 # Copy installed dependencies from dependencies stage
-COPY --from=dependencies /usr/src/app/node_modules ./node_modules
+# COPY --from=builder /usr/src/app/node_modules ./node_modules
+COPY --from=builder /app/node_modules ./node_modules
 
 # Copy built application files
-COPY $CONTAINER_CONTEXT/package.json ./package.json
-COPY $CONTAINER_CONTEXT/public ./public
-COPY $CONTAINER_CONTEXT/.next ./.next
+# COPY $CONTAINER_CONTEXT/package.json ./package.json
+# COPY --from=builder /usr/src/app/dist/apps/vhg/package.json ./package.json
+COPY --from=builder /app/dist/apps/vhg/package.json ./package.json
+# COPY $CONTAINER_CONTEXT/public ./public
+# COPY --from=builder /usr/src/app/dist/apps/vhg/public ./public
+COPY --from=builder /app/dist/apps/vhg/public ./public
+# COPY $CONTAINER_CONTEXT/.next ./.next
+# COPY --from=builder /usr/src/app/dist/apps/vhg/.next ./.next
+COPY --from=builder /app/dist/apps/vhg/.next ./.next
 
 # Run the application under "node" user by default
 RUN chown -R node:node .
